### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Matze997** [XxCreditIsGoodXx/MasterBuilders#1]
Pls fix that [21:22:11] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::getScheduler()" (EXCEPTION) in "plugins/MasterBuilders_dev-4.phar/src/XxCreditIsGoodXx/MasterBuilders/Main" at line 55

**Comment by XxCreditIsGoodXx** [comment]
The plugin was updating please try again if this same thing happens let me know cause I’m doing an update to this plugin

**Comment by Matze997** [comment]
Yeah... Now there's a crash [21:59:14] [Server thread/CRITICAL]:
ParseError: "syntax error, unexpected 'public' (T_PUBLIC)" (EXCEPTION) in
"plugins/MasterBuilders_dev-6.phar/src/XxCreditIsGoodXx/MasterBuilders/Main"
at line 311

XxCreditIsGoodXx <notifications@github.com> schrieb am Mo., 6. Mai 2019,
21:56:

**Comment by XxCreditIsGoodXx** [comment]
Must be a mistake I did while updating the plugin. I’m on workout to fix this error

**Comment by XxCreditIsGoodXx** [comment]
Found the problem and I fix it tell me if a another crash occurs ;)

**Comment by Matze997** [comment]
Ok thanks :D I hope you do more nice plugins like this. :-D

XxCreditIsGoodXx <notifications@github.com> schrieb am Mo., 6. Mai 2019,
22:08:

**Comment by XxCreditIsGoodXx** [comment]
Thank you ;) I’m adding a joinsign [hope you have fun using this plugin]

**Comment by Matze997** [comment]
Mhh there is still a something not working [22:12:13] [Server
thread/CRITICAL]: Error: "Call to undefined method
pocketmine\Server::getScheduler()" (EXCEPTION) in
"plugins/MasterBuilders_dev-11.phar/src/XxCreditIsGoodXx/MasterBuilders/Main"
at line 55

XxCreditIsGoodXx <notifications@github.com> schrieb am Mo., 6. Mai 2019,
22:12:

**Comment by XxCreditIsGoodXx** [comment]
Oh yea you still have that problem I’m on it

**Comment by XxCreditIsGoodXx** [comment]
Before I fix does the plugin work good or stop because of that problem
